# Generated by Django 2.2.1 on 2019-07-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('rates', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('employees', models.CharField(max_length=255)),
                ('services', models.TextField()),
                ('scores', models.CharField(default='5', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('score', models.TextField(max_length=255)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='cats',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
