# Generated by Django 2.2.1 on 2019-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='employees',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agency',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='rates',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.TextField(blank=True, default='5', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
