# Generated by Django 2.2.1 on 2019-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190704_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contacts',
            field=models.TextField(blank=True),
        ),
    ]
