# Generated by Django 2.2.1 on 2019-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_agency_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='image',
            new_name='drive_imgage',
        ),
        migrations.AddField(
            model_name='agency',
            name='origin_image',
            field=models.URLField(blank=True),
        ),
    ]
