# Generated by Django 2.2.1 on 2019-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190705_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='contacts',
            new_name='address',
        ),
        migrations.AddField(
            model_name='agency',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
