# Generated by Django 2.2.1 on 2019-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190706_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='rates',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
